language: bash

sudo: required
services:
  - docker

script:
  - docker build -t marq/boot2docker-nfs .
  - docker run --rm marq/boot2docker-nfs > boot2docker-nfs.iso

after_script:
  - docker image ls
  - ls -l *.iso
